### import packages

In [2]:
import pandas as pd

### import master file

In [3]:
df_master = pd.read_csv("/Users/baselhussein/Projects/pps_isls_2022/data/cleanFiles/df_master.csv")

In [4]:
df_master.head(3)

,ï»¿filename,level,group,Time_Stamp,Transcript,Distal_Goal,Proximal_Goal,Strategy,Problem_Solving_Move,Specific_Deviation_/_Causal_Explanation/_Intervention,Brief_gloss_on_deviation,Disagreements/Questions,Anything_giving_you_pause?_Note_it_here.,filename,Notes_about_any_disagreements_during_process_of_reaching_a_consensus_for_these_final_codes_,Notes
0,BH.P01.S03.SI.01 - Float - Final,float,middle,0:25,BH.01: { Eh (4.8) Um (4.0)\n {((baba pos...,NaN,NaN,NaN,ND-1,NaN,Didn't win,NaN,NaN,NaN,NaN,NaN
1,BH.P01.S03.SI.01 - Float - Final,float,middle,0:45,BH.01: I canât seem to go- get the flag,NaN,NaN,NaN,ND-2/3,NaN,Get to flag,NaN,NaN,NaN,NaN,NaN
2,BH.P01.S03.SI.01 - Float - Final,float,middle,1:29,BH.01: {I wonder if I could try rock is win\n ...,Move self over win item,Change win item,Make ROCK-IS-WIN,AR-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### FLOAT middle summary

In [5]:
### select FLOAT middle

df_float_middle = pd.DataFrame(df_master.loc[(df_master['level'] == "float") & (df_master['group'] == "middle")])
df_float_middle.head(3)

,ï»¿filename,level,group,Time_Stamp,Transcript,Distal_Goal,Proximal_Goal,Strategy,Problem_Solving_Move,Specific_Deviation_/_Causal_Explanation/_Intervention,Brief_gloss_on_deviation,Disagreements/Questions,Anything_giving_you_pause?_Note_it_here.,filename,Notes_about_any_disagreements_during_process_of_reaching_a_consensus_for_these_final_codes_,Notes
0,BH.P01.S03.SI.01 - Float - Final,float,middle,0:25,BH.01: { Eh (4.8) Um (4.0)\n {((baba pos...,NaN,NaN,NaN,ND-1,NaN,Didn't win,NaN,NaN,NaN,NaN,NaN
1,BH.P01.S03.SI.01 - Float - Final,float,middle,0:45,BH.01: I canât seem to go- get the flag,NaN,NaN,NaN,ND-2/3,NaN,Get to flag,NaN,NaN,NaN,NaN,NaN
2,BH.P01.S03.SI.01 - Float - Final,float,middle,1:29,BH.01: {I wonder if I could try rock is win\n ...,Move self over win item,Change win item,Make ROCK-IS-WIN,AR-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
### get Problem solving moves

df_float_middle_summary = df_float_middle[["ï»¿filename", "Problem_Solving_Move"]]
df_float_middle_summary

                                 ï»¿filename Problem_Solving_Move
0           BH.P01.S03.SI.01 - Float - Final                 ND-1
1           BH.P01.S03.SI.01 - Float - Final               ND-2/3
2           BH.P01.S03.SI.01 - Float - Final                 AR-1
3           BH.P01.S03.SI.01 - Float - Final               ND-2/3
4           BH.P01.S03.SI.01 - Float - Final               CE-2/3
..                                       ...                  ...
81  RH.P02.S03 - Float, NOWEB-NOCONF - Final                 ND-1
82  RH.P02.S03 - Float, NOWEB-NOCONF - Final                 AR-1
83  RH.P02.S03 - Float, NOWEB-NOCONF - Final                 ND-1
84  RH.P02.S03 - Float, NOWEB-NOCONF - Final                 AR-1
85  RH.P02.S03 - Float, NOWEB-NOCONF - Final                   SR

[86 rows x 2 columns]

In [7]:
df_float_middle_move = pd.DataFrame(df_float_middle["Problem_Solving_Move"])
df_float_middle_move.head()

  Problem_Solving_Move
0                 ND-1
1               ND-2/3
2                 AR-1
3               ND-2/3
4               CE-2/3

In [8]:
### get unique moves

categories_moves = df_float_middle_move['Problem_Solving_Move'].unique()
categories_moves

array(['ND-1', 'ND-2/3', 'AR-1', 'CE-2/3', 'SR', 'CE-1', 'AR-2/3'],
      dtype=object)

In [9]:
### get matrix count of moves

df_float_middle_move = pd.get_dummies(df_float_middle_move.Problem_Solving_Move).reindex(columns=categories_moves, fill_value=0)

In [10]:
df_float_middle_move

    ND-1  ND-2/3  AR-1  CE-2/3  SR  CE-1  AR-2/3
0      1       0     0       0   0     0       0
1      0       1     0       0   0     0       0
2      0       0     1       0   0     0       0
3      0       1     0       0   0     0       0
4      0       0     0       1   0     0       0
..   ...     ...   ...     ...  ..   ...     ...
81     1       0     0       0   0     0       0
82     0       0     1       0   0     0       0
83     1       0     0       0   0     0       0
84     0       0     1       0   0     0       0
85     0       0     0       0   1     0       0

[86 rows x 7 columns]

In [11]:
### combine counts with moves

df_float_middle_summary_moves = pd.concat([df_float_middle_summary, df_float_middle_move], axis=1)
df_float_middle_summary_moves

,ï»¿filename,Problem_Solving_Move,ND-1,ND-2/3,AR-1,CE-2/3,SR,CE-1,AR-2/3
0,BH.P01.S03.SI.01 - Float - Final,ND-1,1,0,0,0,0,0,0
1,BH.P01.S03.SI.01 - Float - Final,ND-2/3,0,1,0,0,0,0,0
2,BH.P01.S03.SI.01 - Float - Final,AR-1,0,0,1,0,0,0,0
3,BH.P01.S03.SI.01 - Float - Final,ND-2/3,0,1,0,0,0,0,0
4,BH.P01.S03.SI.01 - Float - Final,CE-2/3,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...
81,"RH.P02.S03 - Float, NOWEB-NOCONF - Final",ND-1,1,0,0,0,0,0,0
82,"RH.P02.S03 - Float, NOWEB-NOCONF - Final",AR-1,0,0,1,0,0,0,0
83,"RH.P02.S03 - Float, NOWEB-NOCONF - Final",ND-1,1,0,0,0,0,0,0
84,"RH.P02.S03 - Float, NOWEB-NOCONF - Final",AR-1,0,0,1,0,0,0,0
85,"RH.P02.S03 - Float, NOWEB-NOCONF - Final",SR,0,0,0,0,1,0,0

In [12]:
### drop irrelevant values

df_float_middle_summary_moves.drop('Problem_Solving_Move', axis=1, inplace=True)

In [13]:
df_float_middle_summary_moves

,ï»¿filename,ND-1,ND-2/3,AR-1,CE-2/3,SR,CE-1,AR-2/3
0,BH.P01.S03.SI.01 - Float - Final,1,0,0,0,0,0,0
1,BH.P01.S03.SI.01 - Float - Final,0,1,0,0,0,0,0
2,BH.P01.S03.SI.01 - Float - Final,0,0,1,0,0,0,0
3,BH.P01.S03.SI.01 - Float - Final,0,1,0,0,0,0,0
4,BH.P01.S03.SI.01 - Float - Final,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...
81,"RH.P02.S03 - Float, NOWEB-NOCONF - Final",1,0,0,0,0,0,0
82,"RH.P02.S03 - Float, NOWEB-NOCONF - Final",0,0,1,0,0,0,0
83,"RH.P02.S03 - Float, NOWEB-NOCONF - Final",1,0,0,0,0,0,0
84,"RH.P02.S03 - Float, NOWEB-NOCONF - Final",0,0,1,0,0,0,0
85,"RH.P02.S03 - Float, NOWEB-NOCONF - Final",0,0,0,0,1,0,0

In [14]:
### get count by player

byPlayer = df_float_middle_summary_moves.groupby('ï»¿filename')

In [15]:
df_float_middle_sum = pd.DataFrame(byPlayer.sum())
df_float_middle_sum

,ND-1,ND-2/3,AR-1,CE-2/3,SR,CE-1,AR-2/3
ï»¿filename,,,,,,,
BH.P01.S03.SI.01 - Float - Final,2,3,4,1,1,0,0
BH.P02.S02.SI.01 - Float - Final,1,1,1,1,1,2,1
JV.P01.S02.SI.01.Float - Final,1,0,0,1,1,0,1
JV.P02.S02.SI.01.Float - Final,1,0,2,1,1,0,0
JV.P03.S03.SI.01.Float - Final,3,0,3,1,1,0,0
JV.P04.S02.SI.01.Float - Final,3,0,2,1,1,0,1
MG.P01.S03 - Float - Final,7,0,8,1,1,0,0
MG.P02.S03 - Float - Final,2,3,2,1,1,1,2
MG.P03.S01 - Float - Final,2,0,2,1,1,0,0
"RH.P02.S03 - Float, NOWEB-NOCONF - Final",3,0,3,0,1,0,0

In [16]:
### get mean moves by player

df_float_middle_sum.mean()

ND-1      2.5
ND-2/3    0.7
AR-1      2.7
CE-2/3    0.9
SR        1.0
CE-1      0.3
AR-2/3    0.5
dtype: float64

In [17]:
### get std moves between players

df_float_middle_sum.std()

ND-1      1.779513
ND-2/3    1.251666
AR-1      2.162817
CE-2/3    0.316228
SR        0.000000
CE-1      0.674949
AR-2/3    0.707107
dtype: float64

### ######################################################

### FLOAT college

In [18]:
### get FLOAT college data

df_float_college = pd.DataFrame(df_master.loc[(df_master['level'] == "float") & (df_master['group'] == "college")])
df_float_college.head()

,ï»¿filename,level,group,Time_Stamp,Transcript,Distal_Goal,Proximal_Goal,Strategy,Problem_Solving_Move,Specific_Deviation_/_Causal_Explanation/_Intervention,Brief_gloss_on_deviation,Disagreements/Questions,Anything_giving_you_pause?_Note_it_here.,filename,Notes_about_any_disagreements_during_process_of_reaching_a_consensus_for_these_final_codes_,Notes
86,BH.C.P01.S02 - Final,float,college,0:38,P01: I donât know {ok wait (.) O::h }\n ...,Move self over win item,Move self over flag,Move baba over flag,ND-2/3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,BH.C.P01.S02 - Final,float,college,NaN,so baba is float,NaN,NaN,NaN,CE-2/3,NaN,we argue for CE3 because we feel like the stat...,NaN,NaN,NaN,NaN,NaN
88,BH.C.P01.S02 - Final,float,college,1:13,P01: so Iâm kind of tryin to figure out what...,Move self over win item,Figure out FLOAT mechanic,Have flag and rock at same coordinate when bab...,AR-1,NaN,we argue that its not AR2 because there is not...,NaN,NaN,NaN,NaN,NaN
89,BH.C.P01.S02 - Final,float,college,1:23,P01: (1.8) Baba is float (.),NaN,NaN,NaN,ND-1,NaN,Congratulations does not display,NaN,NaN,NaN,NaN,NaN
90,BH.C.P01.S02 - Final,float,college,1:28,P01: so I canât get rid of baba is float (.)...,NaN,NaN,NaN,ND-2/3,NaN,BABA IS FLOAT is unchangable,NaN,NaN,NaN,NaN,NaN

In [19]:
### get moves

df_float_college_summary = df_float_college[["ï»¿filename", "Problem_Solving_Move"]]
df_float_college_summary

                    ï»¿filename Problem_Solving_Move
86         BH.C.P01.S02 - Final               ND-2/3
87         BH.C.P01.S02 - Final               CE-2/3
88         BH.C.P01.S02 - Final                 AR-1
89         BH.C.P01.S02 - Final                 ND-1
90         BH.C.P01.S02 - Final               ND-2/3
..                          ...                  ...
186  RH.C.P03.S03.SI.01 - Final                 AR-1
187  RH.C.P03.S03.SI.01 - Final                 AR-1
188  RH.C.P03.S03.SI.01 - Final                 ND-1
189  RH.C.P03.S03.SI.01 - Final                 AR-1
190  RH.C.P03.S03.SI.01 - Final                   SR

[105 rows x 2 columns]

In [20]:
df_float_college_move = pd.DataFrame(df_float_college["Problem_Solving_Move"])

In [21]:
#df_float_college_move.head()

In [22]:
### get unique moves

categories_moves_float_college = df_float_college_move['Problem_Solving_Move'].unique()
categories_moves_float_college

array(['ND-2/3', 'CE-2/3', 'AR-1', 'ND-1', 'AR-2/3', 'SR', 'CE-1'],
      dtype=object)

In [23]:
### get matrix count of moves

df_float_college_move = pd.get_dummies(df_float_college_move.Problem_Solving_Move).reindex(columns=categories_moves_float_college, fill_value=0)

In [24]:
df_float_college_move

     ND-2/3  CE-2/3  AR-1  ND-1  AR-2/3  SR  CE-1
86        1       0     0     0       0   0     0
87        0       1     0     0       0   0     0
88        0       0     1     0       0   0     0
89        0       0     0     1       0   0     0
90        1       0     0     0       0   0     0
..      ...     ...   ...   ...     ...  ..   ...
186       0       0     1     0       0   0     0
187       0       0     1     0       0   0     0
188       0       0     0     1       0   0     0
189       0       0     1     0       0   0     0
190       0       0     0     0       0   1     0

[105 rows x 7 columns]

In [25]:
### combine moves and counts

df_float_college_summary_moves = pd.concat([df_float_college_summary, df_float_college_move], axis=1)
df_float_college_summary_moves

,ï»¿filename,Problem_Solving_Move,ND-2/3,CE-2/3,AR-1,ND-1,AR-2/3,SR,CE-1
86,BH.C.P01.S02 - Final,ND-2/3,1,0,0,0,0,0,0
87,BH.C.P01.S02 - Final,CE-2/3,0,1,0,0,0,0,0
88,BH.C.P01.S02 - Final,AR-1,0,0,1,0,0,0,0
89,BH.C.P01.S02 - Final,ND-1,0,0,0,1,0,0,0
90,BH.C.P01.S02 - Final,ND-2/3,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
186,RH.C.P03.S03.SI.01 - Final,AR-1,0,0,1,0,0,0,0
187,RH.C.P03.S03.SI.01 - Final,AR-1,0,0,1,0,0,0,0
188,RH.C.P03.S03.SI.01 - Final,ND-1,0,0,0,1,0,0,0
189,RH.C.P03.S03.SI.01 - Final,AR-1,0,0,1,0,0,0,0
190,RH.C.P03.S03.SI.01 - Final,SR,0,0,0,0,0,1,0

In [26]:
df_float_college_summary_moves.drop('Problem_Solving_Move', axis=1, inplace=True)

In [27]:
#df_float_college_summary_moves

In [28]:
### get counts by player

byPlayer_float_college = df_float_college_summary_moves.groupby('ï»¿filename')

In [29]:
df_float_college_sum = pd.DataFrame(byPlayer_float_college.sum())
df_float_college_sum

                            ND-2/3  CE-2/3  AR-1  ND-1  AR-2/3  SR  CE-1
ï»¿filename
BH.C.P01.S02 - Final             2       3     5     4       1   1     0
BH.C.P02.S02 - Final             1       1     1     0       0   1     0
BH.C.P03.S03 - Final             0       1     3     4       1   1     0
JV.C.P01.S03 - Final             0       1     3     3       0   1     0
JV.C.P02.S02 - Final             1       2     3     4       0   1     1
JV.C.P03.S02 - Final             0       0     4     5       0   1     0
MG.C.P01.S02 - Final             2       2     5     5       1   1     0
MG.C.P02.S01 - Final             0       1     0     1       1   1     0
RH.C.P01.S02 - Final             0       1     1     1       0   1     0
RH.C.P02.SI.01 - Final           0       0     1     1       0   1     1
RH.C.P03.S03.SI.01 - Final       1       1     6     6       2   1     0

In [30]:
### get mean by player 

df_float_college_sum.mean()

ND-2/3    0.636364
CE-2/3    1.181818
AR-1      2.909091
ND-1      3.090909
AR-2/3    0.545455
SR        1.000000
CE-1      0.181818
dtype: float64

In [31]:
### get std between players

df_float_college_sum.std()

ND-2/3    0.809040
CE-2/3    0.873863
AR-1      1.972539
ND-1      2.022600
AR-2/3    0.687552
SR        0.000000
CE-1      0.404520
dtype: float64

### ##################################################

### CHANGELESS - MIDDLE

In [32]:
### get CHANGELESS middle

df_changeless_middle = pd.DataFrame(df_master.loc[(df_master['level'] == "changeless") & (df_master['group'] == "middle")])
df_changeless_middle.head()

,ï»¿filename,level,group,Time_Stamp,Transcript,Distal_Goal,Proximal_Goal,Strategy,Problem_Solving_Move,Specific_Deviation_/_Causal_Explanation/_Intervention,Brief_gloss_on_deviation,Disagreements/Questions,Anything_giving_you_pause?_Note_it_here.,filename,Notes_about_any_disagreements_during_process_of_reaching_a_consensus_for_these_final_codes_,Notes
191,NaN,changeless,middle,0:22,JV2: that did {nothing } (3.0)\n {ROCK-IS-ROCK},NaN,NaN,NaN,ND-1,NaN,nothing happened to the ROCK\nor anywhere else...,NaN,NaN,Middle-JV.P01.S02.TL.09.NOWEB - FINAL,NaN,NaN
192,NaN,changeless,middle,0:30,JV2: FLA::G IS RO:CK? (.) where is the fla:g,NaN,NaN,NaN,ND-1,NaN,No flag in task environment,NaN,NaN,Middle-JV.P01.S02.TL.09.NOWEB - FINAL,NaN,NaN
193,NaN,changeless,middle,0:35,JV2: >well what if< (1.0) {(.) } (1.0)\n {FLAG...,Move self over flag,Locate flag,Break FLAG IS ROCK,AR-1,NaN,NaN,NaN,NaN,Middle-JV.P01.S02.TL.09.NOWEB - FINAL,NaN,NaN
194,NaN,changeless,middle,0:40,JV2: (1.0) {(.) } (1.0)\n {FLAG-IS-ROCK},NaN,NaN,NaN,ND-1,NaN,No flag appeared,NaN,NaN,Middle-JV.P01.S02.TL.09.NOWEB - FINAL,NaN,NaN
195,NaN,changeless,middle,0:42,JV2: {huh } (\n {ROCK/IS-ROCK},Move self over flag,Locate flag,Break ROCK IS ROCK,AR-1,NaN,NaN,NaN,NaN,Middle-JV.P01.S02.TL.09.NOWEB - FINAL,NaN,NaN

In [33]:
### get moves

df_changeless_middle_summary = df_changeless_middle[["filename", "Problem_Solving_Move"]]
df_changeless_middle_summary

                                         filename Problem_Solving_Move
191         Middle-JV.P01.S02.TL.09.NOWEB - FINAL                 ND-1
192         Middle-JV.P01.S02.TL.09.NOWEB - FINAL                 ND-1
193         Middle-JV.P01.S02.TL.09.NOWEB - FINAL                 AR-1
194         Middle-JV.P01.S02.TL.09.NOWEB - FINAL                 ND-1
195         Middle-JV.P01.S02.TL.09.NOWEB - FINAL                 AR-1
..                                            ...                  ...
299  Middle-RH.P02.S02.NOWEB-NOCONF.TL.09 - Final                 ND-1
300  Middle-RH.P02.S02.NOWEB-NOCONF.TL.09 - Final                 AR-1
301  Middle-RH.P02.S02.NOWEB-NOCONF.TL.09 - Final                 ND-1
302  Middle-RH.P02.S02.NOWEB-NOCONF.TL.09 - Final               AR-2/3
303  Middle-RH.P02.S02.NOWEB-NOCONF.TL.09 - Final                   SR

[113 rows x 2 columns]

In [34]:
df_changeless_middle_move = pd.DataFrame(df_changeless_middle["Problem_Solving_Move"])

In [35]:
#df_changeless_middle_move

In [36]:
### get unique moves

categories_moves_changeless_middle = df_changeless_middle_move['Problem_Solving_Move'].unique()
categories_moves_changeless_middle

array(['ND-1', 'AR-1', 'SR', 'ND-2/3', 'CE-1', 'AR-2/3', 'CE-2/3'],
      dtype=object)

In [37]:
### get unique counts

df_changeless_middle_move = pd.get_dummies(df_changeless_middle_move.Problem_Solving_Move).reindex(columns=categories_moves_changeless_middle, fill_value=0)

In [38]:
df_changeless_middle_move

     ND-1  AR-1  SR  ND-2/3  CE-1  AR-2/3  CE-2/3
191     1     0   0       0     0       0       0
192     1     0   0       0     0       0       0
193     0     1   0       0     0       0       0
194     1     0   0       0     0       0       0
195     0     1   0       0     0       0       0
..    ...   ...  ..     ...   ...     ...     ...
299     1     0   0       0     0       0       0
300     0     1   0       0     0       0       0
301     1     0   0       0     0       0       0
302     0     0   0       0     0       1       0
303     0     0   1       0     0       0       0

[113 rows x 7 columns]

In [39]:
### combine counts and moves

df_changeless_middle_summary_moves = pd.concat([df_changeless_middle_summary, df_changeless_middle_move], axis=1)
df_changeless_middle_summary_moves

,filename,Problem_Solving_Move,ND-1,AR-1,SR,ND-2/3,CE-1,AR-2/3,CE-2/3
191,Middle-JV.P01.S02.TL.09.NOWEB - FINAL,ND-1,1,0,0,0,0,0,0
192,Middle-JV.P01.S02.TL.09.NOWEB - FINAL,ND-1,1,0,0,0,0,0,0
193,Middle-JV.P01.S02.TL.09.NOWEB - FINAL,AR-1,0,1,0,0,0,0,0
194,Middle-JV.P01.S02.TL.09.NOWEB - FINAL,ND-1,1,0,0,0,0,0,0
195,Middle-JV.P01.S02.TL.09.NOWEB - FINAL,AR-1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
299,Middle-RH.P02.S02.NOWEB-NOCONF.TL.09 - Final,ND-1,1,0,0,0,0,0,0
300,Middle-RH.P02.S02.NOWEB-NOCONF.TL.09 - Final,AR-1,0,1,0,0,0,0,0
301,Middle-RH.P02.S02.NOWEB-NOCONF.TL.09 - Final,ND-1,1,0,0,0,0,0,0
302,Middle-RH.P02.S02.NOWEB-NOCONF.TL.09 - Final,AR-2/3,0,0,0,0,0,1,0
303,Middle-RH.P02.S02.NOWEB-NOCONF.TL.09 - Final,SR,0,0,1,0,0,0,0

In [40]:
df_changeless_middle_summary_moves.drop('Problem_Solving_Move', axis=1, inplace=True)

In [41]:
#df_changeless_middle_summary_moves

In [42]:
### get moves by player

byPlayer_changeless_middle = df_changeless_middle_summary_moves.groupby('filename')

In [43]:
df_changeless_middle_sum = pd.DataFrame(byPlayer_changeless_middle.sum())

In [44]:
df_changeless_middle_sum

,ND-1,AR-1,SR,ND-2/3,CE-1,AR-2/3,CE-2/3
filename,,,,,,,
Middle-JV.P01.S02.TL.09.NOWEB - FINAL,6,5,1,0,0,0,0
Middle-JV.P02-FINAL,8,7,1,2,1,3,0
Middle-JV.P03.S02 - FINAL,6,5,1,1,1,0,0
Middle-JV.P04.S03-FINAL,1,1,1,0,0,0,0
Middle-MG.P02-FINAL,5,4,1,5,1,3,2
Middle-MG.P03.S02-FINAL,4,3,1,0,1,1,0
Middle-RH.P01.S03 - FINAL,7,7,1,1,0,1,1
Middle-RH.P02.S02.NOWEB-NOCONF.TL.09 - Final,6,5,1,0,0,1,0

In [45]:
### get mean by player

df_changeless_middle_sum.mean()

ND-1      5.375
AR-1      4.625
SR        1.000
ND-2/3    1.125
CE-1      0.500
AR-2/3    1.125
CE-2/3    0.375
dtype: float64

In [46]:
### get std between players

df_changeless_middle_sum.std()

ND-1      2.133910
AR-1      1.995531
SR        0.000000
ND-2/3    1.726888
CE-1      0.534522
AR-2/3    1.246423
CE-2/3    0.744024
dtype: float64

### #######################################################

### CHANGELESS - college

In [47]:
df_changeless_college = pd.DataFrame(df_master.loc[(df_master['level'] == "changeless") & (df_master['group'] == "college")])
df_changeless_college.head(3)

,ï»¿filename,level,group,Time_Stamp,Transcript,Distal_Goal,Proximal_Goal,Strategy,Problem_Solving_Move,Specific_Deviation_/_Causal_Explanation/_Intervention,Brief_gloss_on_deviation,Disagreements/Questions,Anything_giving_you_pause?_Note_it_here.,filename,Notes_about_any_disagreements_during_process_of_reaching_a_consensus_for_these_final_codes_,Notes
304,NaN,changeless,college,0:19,"P01: {(2.0)\n {((pronouned blink, backtracks, ...",NaN,NaN,NaN,ND-1,NaN,Flag turned to rock,NaN,NaN,College-BH.C.P01.S02.TL.09-FINAL,NaN,NaN
305,NaN,changeless,college,0:21,P01: {(.) } (2.0) \n {FLAG-IS/ROCK},Move self over win item,Obtain flag,Break FLAG IS ROCK,AR-1,NaN,NaN,NaN,NaN,College-BH.C.P01.S02.TL.09-FINAL,NaN,NaN
306,NaN,changeless,college,NaN,{(.) } (1.0)\n{FLAG-IS-ROCK},NaN,NaN,NaN,ND-1,NaN,Rock did not convert to flag with rule change,NaN,NaN,College-BH.C.P01.S02.TL.09-FINAL,NaN,Justification: undoing previous action

In [48]:
### get moves

df_changeless_college_summary = df_changeless_college[["filename", "Problem_Solving_Move"]]
df_changeless_college_summary

                               filename Problem_Solving_Move
304    College-BH.C.P01.S02.TL.09-FINAL                 ND-1
305    College-BH.C.P01.S02.TL.09-FINAL                 AR-1
306    College-BH.C.P01.S02.TL.09-FINAL                 ND-1
307    College-BH.C.P01.S02.TL.09-FINAL                 AR-1
308    College-BH.C.P01.S02.TL.09-FINAL                   SR
..                                  ...                  ...
407  College-RH.C.P02.S01.TL.09 - Final                 AR-1
408  College-RH.C.P02.S01.TL.09 - Final                 ND-1
409  College-RH.C.P02.S01.TL.09 - Final               CE-2/3
410  College-RH.C.P02.S01.TL.09 - Final                 AR-1
411  College-RH.C.P02.S01.TL.09 - Final                   SR

[108 rows x 2 columns]

In [49]:
df_changeless_college_move = pd.DataFrame(df_changeless_college["Problem_Solving_Move"])
#df_changeless_college_move

In [50]:
### get unique moves

categories_moves_changeless_college = df_changeless_college_move['Problem_Solving_Move'].unique()
categories_moves_changeless_college

array(['ND-1', 'AR-1', 'SR', 'ND-2/3', 'CE-2/3', 'CE-1', 'AR-2/3'],
      dtype=object)

In [51]:
### get matrix counts of moves

df_changeless_college_move = pd.get_dummies(df_changeless_college_move.Problem_Solving_Move).reindex(columns=categories_moves_changeless_college, fill_value=0)

In [52]:
df_changeless_college_move

     ND-1  AR-1  SR  ND-2/3  CE-2/3  CE-1  AR-2/3
304     1     0   0       0       0     0       0
305     0     1   0       0       0     0       0
306     1     0   0       0       0     0       0
307     0     1   0       0       0     0       0
308     0     0   1       0       0     0       0
..    ...   ...  ..     ...     ...   ...     ...
407     0     1   0       0       0     0       0
408     1     0   0       0       0     0       0
409     0     0   0       0       1     0       0
410     0     1   0       0       0     0       0
411     0     0   1       0       0     0       0

[108 rows x 7 columns]

In [53]:
### combine moves and counts

df_changeless_college_summary_moves = pd.concat([df_changeless_college_summary, df_changeless_college_move], axis=1)
#df_changeless_college_summary_moves

In [54]:
df_changeless_college_summary_moves.drop('Problem_Solving_Move', axis=1, inplace=True)

In [55]:
#df_changeless_college_summary_moves

In [56]:
### get counts by player

byPlayer_changeless_college = df_changeless_college_summary_moves.groupby('filename')

In [57]:
df_changeless_college_sum = pd.DataFrame(byPlayer_changeless_college.sum())

In [58]:
df_changeless_college_sum

,ND-1,AR-1,SR,ND-2/3,CE-2/3,CE-1,AR-2/3
filename,,,,,,,
College-BH.C.P01.S02.TL.09-FINAL,2,2,1,0,0,0,0
College-BH.C.P02.S02.TL.09-FINAL,4,6,1,2,1,1,0
College-BH.C.P03.S02.TL09 - FINAL,3,3,1,0,1,0,1
College-JV.C.P01.S02.TL.09 - FINAL,11,10,1,2,1,0,1
College-JV.C.P02.S03 - Final,2,2,1,1,0,0,0
College-JV.C.P03.S03.TL.09 - Final,2,2,1,0,0,0,0
College-MG.C.P01.S02_TL09 - Final,5,5,1,4,1,1,0
College-RH.C.P01.S01.TL.09 - Final,4,3,1,1,1,0,1
College-RH.C.P02.S01.TL.09 - Final,4,5,1,2,2,0,0

In [59]:
### get mean by player

df_changeless_college_sum.mean()

ND-1      4.111111
AR-1      4.222222
SR        1.000000
ND-2/3    1.333333
CE-2/3    0.777778
CE-1      0.222222
AR-2/3    0.333333
dtype: float64

In [60]:
### get std between players

df_changeless_college_sum.std()

ND-1      2.803767
AR-1      2.635231
SR        0.000000
ND-2/3    1.322876
CE-2/3    0.666667
CE-1      0.440959
AR-2/3    0.500000
dtype: float64